#services:
#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: social-media-database
#    ports:
#      - "3306:3306"
#
#  rest-app:
#    build: .
#    depends_on:
#      - mysql
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/social-media-database
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    ports:
#      - "8080:8080"